program BoardCafeControl;

uses
  Vcl.Forms,
  BCC.View.FrameBase in 'Base\View\BCC.View.FrameBase.pas' {FraBase: TFrame},
  BCC.Conexao.DAO.Dados in 'Conexao\BCC.Conexao.DAO.Dados.pas' {DmDados: TDataModule},
  BCC.Campeonatos.View.Cadastro in 'Campeonatos\View\BCC.Campeonatos.View.Cadastro.pas' {FrmCadastroCampeonato: TFrame},
  BCC.Campeonatos.View.Classificacao in 'Campeonatos\View\BCC.Campeonatos.View.Classificacao.pas' {FrmClassificacaoCampeonato: TFrame},
  BCC.Campeonatos.View.Inscricao in 'Campeonatos\View\BCC.Campeonatos.View.Inscricao.pas' {FrmInscricaoCampeonato: TFrame},
  BCC.Salas.View.Cadastro in 'Salas\View\BCC.Salas.View.Cadastro.pas' {FrmCadastroSala: TFrame},
  BCC.Salas.View.Reserva in 'Salas\View\BCC.Salas.View.Reserva.pas' {FrmReservaSala: TFrame},
  BCC.View.FormBase in 'Base\View\BCC.View.FormBase.pas' {FrmBase},
  BCC.Clientes.View.Cadastro in 'Clientes\View\BCC.Clientes.View.Cadastro.pas' {FrmCadastroCliente: TFrame},
  BCC.Funcionarios.View.Cadastro in 'Funcionarios\View\BCC.Funcionarios.View.Cadastro.pas' {FrmCadastroFuncionarios: TFrame},
  BCC.Jogos.View.Cadastro in 'Jogo\View\BCC.Jogos.View.Cadastro.pas' {FrmCadastroJogo: TFrame},
  BCC.Model.Jogo in 'Jogo\Model\BCC.Model.Jogo.pas',
  BCC.Mesa.View.Pedido in 'Mesa\View\BCC.Mesa.View.Pedido.pas' {FrmLancarPedidoMesa: TFrame},
  BCC.View.Login in 'Principal\View\BCC.View.Login.pas' {FrmLogin},
  BCC.View.Menu in 'Principal\View\BCC.View.Menu.pas' {FrmMenu},
  BCC.Produtos.View.Cadastro in 'Produtos\View\BCC.Produtos.View.Cadastro.pas' {FrmCadastroProduto: TFrame},
  BCC.Model.Usuario in 'Base\Model\BCC.Model.Usuario.pas',
  BCC.Model.Campeonato in 'Campeonatos\Model\BCC.Model.Campeonato.pas',
  BCC.Model.Cliente in 'Clientes\Model\BCC.Model.Cliente.pas',
  BCC.Model.Funcionario in 'Funcionarios\Model\BCC.Model.Funcionario.pas',
  BCC.Model.Endereco in 'Base\Model\BCC.Model.Endereco.pas',
  BCC.Model.Mesa in 'Mesa\Model\BCC.Model.Mesa.pas',
  BCC.Model.Produto in 'Produtos\Model\BCC.Model.Produto.pas',
  BCC.DAO.Cliente in 'Clientes\DAO\BCC.DAO.Cliente.pas' {DmCliente: TDataModule},
  BCC.DAO.Usuario in 'Base\DAO\BCC.DAO.Usuario.pas' {DmUsuario: TDataModule},
  BCC.DAO.Funcionario in 'Funcionarios\DAO\BCC.DAO.Funcionario.pas' {DmFuncionario: TDataModule},
  BCC.View.ConsultaBase in 'Base\View\BCC.View.ConsultaBase.pas' {FrmConsultaBase},
  BCC.Clientes.View.Consulta in 'Clientes\View\BCC.Clientes.View.Consulta.pas' {FrmConsultaCliente},
  BCC.DAO.Sala in 'Salas\DAO\BCC.DAO.Sala.pas' {DmSala: TDataModule},
  BCC.Model.Sala in 'Salas\Model\BCC.Model.Sala.pas',
  BCC.Salas.View.Consulta in 'Salas\View\BCC.Salas.View.Consulta.pas' {FrmConsultaSala},
  BCC.Funcionarios.View.Consulta in 'Funcionarios\View\BCC.Funcionarios.View.Consulta.pas' {FrmConsultaFuncionario},
  BCC.DAO.Jogo in 'Jogo\DAO\BCC.DAO.Jogo.pas' {DmJogo: TDataModule},
  BCC.Jogos.View.Consulta in 'Jogo\View\BCC.Jogos.View.Consulta.pas' {FrmConsultaJogo},
  BCC.DAO.Campeonatos in 'Campeonatos\DAO\BCC.DAO.Campeonatos.pas' {DmCampeonato: TDataModule},
  BCC.Campeonatos.View.Consulta in 'Campeonatos\View\BCC.Campeonatos.View.Consulta.pas' {FrmConsultaCampeonato},
  BCC.DAO.Competidores in 'Campeonatos\DAO\BCC.DAO.Competidores.pas' {DmCompetidores: TDataModule},
  BCC.Model.Competidores in 'Campeonatos\Model\BCC.Model.Competidores.pas',
  BCC.Controller.Campeonatos in 'Campeonatos\Controller\BCC.Controller.Campeonatos.pas',
  BCC.Sala.Model.Reserva in 'Salas\Model\BCC.Sala.Model.Reserva.pas',
  BCC.Sala.DAO.Reserva in 'Salas\DAO\BCC.Sala.DAO.Reserva.pas' {DmReserva: TDataModule},
  BCC.Salas.View.ConsultaReserva in 'Salas\View\BCC.Salas.View.ConsultaReserva.pas' {FrmConsultaReserva},
  BCC.Campeonatos.View.Controle in 'Campeonatos\View\BCC.Campeonatos.View.Controle.pas' {FrmControleCampeonato: TFrame},
  BCC.DAO.Produto in 'Produtos\DAO\BCC.DAO.Produto.pas' {DmProduto: TDataModule},
  BCC.Produtos.View.Consulta in 'Produtos\View\BCC.Produtos.View.Consulta.pas' {FrmConsultaProduto},
  BCC.DAO.Servico in 'Servico\DAO\BCC.DAO.Servico.pas' {DmServico: TDataModule},
  BCC.Model.Servico in 'Servico\Model\BCC.Model.Servico.pas',
  BCC.Servico.View.Cadastro in 'Servico\View\BCC.Servico.View.Cadastro.pas' {FrmCadastroServico: TFrame},
  BCC.Servico.View.Consulta in 'Servico\View\BCC.Servico.View.Consulta.pas' {FrmConsultaServico},
  BCC.Produto.Model.Promocao in 'Produtos\Model\BCC.Produto.Model.Promocao.pas',
  BCC.Produto.DAO.Promocao in 'Produtos\DAO\BCC.Produto.DAO.Promocao.pas' {DmPromocao: TDataModule},
  BCC.Controller.Mesa in 'Mesa\Controller\BCC.Controller.Mesa.pas',
  BCC.DAO.Mesa in 'Mesa\DAO\BCC.DAO.Mesa.pas' {DmMesa: TDataModule},
  BCC.Produtos.View.CadastroPromocao in 'Produtos\View\BCC.Produtos.View.CadastroPromocao.pas' {FrmPromocao: TFrame},
  BCC.Produtos.View.ConsultaPromocao in 'Produtos\View\BCC.Produtos.View.ConsultaPromocao.pas' {FrmConsultaRegraPromocao},
  BCC.Mesa.View.Consulta in 'Mesa\View\BCC.Mesa.View.Consulta.pas' {FrmConsultaMesa},
  BCC.Caixa.View.Abertura in 'Caixa\View\BCC.Caixa.View.Abertura.pas' {FrmAbreCaixa},
  BCC.Model.Caixa in 'Caixa\Model\BCC.Model.Caixa.pas',
  BCC.DAO.Caixa in 'Caixa\DAO\BCC.DAO.Caixa.pas' {DmCaixa: TDataModule},
  BCC.Mesa.View.Identificacao in 'Mesa\View\BCC.Mesa.View.Identificacao.pas' {FrmIdentificacaoMesa},
  BCC.Caixa.DAO.Movimentacao in 'Caixa\DAO\BCC.Caixa.DAO.Movimentacao.pas' {DmMovimentacao: TDataModule},
  BCC.Caixa.Model.Movimentacao in 'Caixa\Model\BCC.Caixa.Model.Movimentacao.pas',
  BCC.Caixa.View.Menu in 'Caixa\View\BCC.Caixa.View.Menu.pas' {FrmMenuCaixa},
  BCC.Relatorios.Controller.Excell in 'Relatorio\Controller\BCC.Relatorios.Controller.Excell.pas',
  BCC.Mesa.View.Fechamento in 'Mesa\View\BCC.Mesa.View.Fechamento.pas' {FrmFechaMesa},
  BCC.Produtos.View.LancaEstoque in 'Produtos\View\BCC.Produtos.View.LancaEstoque.pas' {FrmLancaEstoque},
  BCC.Campeonatos.View.AdicionaPartida in 'Campeonatos\View\BCC.Campeonatos.View.AdicionaPartida.pas' {FrmAdicionaPartida},
  BCC.Campeonatos.View.ControleBase in 'Campeonatos\View\BCC.Campeonatos.View.ControleBase.pas' {FraControleCampeonato: TFrame},
  BCC.Campeonatos.View.ControlePontos in 'Campeonatos\View\BCC.Campeonatos.View.ControlePontos.pas' {FraControleCampeonatoPontos: TFrame},
  BCC.Campeonatos.View.ControleEliminatoria in 'Campeonatos\View\BCC.Campeonatos.View.ControleEliminatoria.pas' {FraControleCampeonatoEliminatoria: TFrame},
  BCC.Relatorio.View.RelBase in 'Relatorio\View\BCC.Relatorio.View.RelBase.pas' {FraRelBase: TFrame},
  BCC.Relatorio.View.VendasDia in 'Relatorio\View\BCC.Relatorio.View.VendasDia.pas' {FraRelVendasDia: TFrame},
  BCC.Relatorio.View.ProdutosVendidos in 'Relatorio\View\BCC.Relatorio.View.ProdutosVendidos.pas' {FraRelProdutosVendidos: TFrame},
  BCC.Principal.Funcional.Validacoes in 'Principal\Funcional\BCC.Principal.Funcional.Validacoes.pas',
  BCC.Model.Contas in 'Contas\Model\BCC.Model.Contas.pas',
  BCC.DAO.Contas in 'Contas\DAO\BCC.DAO.Contas.pas' {DmContas: TDataModule},
  BCC.Contas.View.Cadastro in 'Contas\View\BCC.Contas.View.Cadastro.pas' {FrmContas: TFrame},
  BCC.Contas.View.Consulta in 'Contas\View\BCC.Contas.View.Consulta.pas' {FrmConsultaConta},
  BCC.Relatorio.Report.JogosPedidos in 'Relatorio\Report\BCC.Relatorio.Report.JogosPedidos.pas' {RelJogoSolicitado},
  BCC.Relatorio.View.JogosPedidos in 'Relatorio\View\BCC.Relatorio.View.JogosPedidos.pas' {FraRelJogosSolicitados: TFrame},
  BCC.Relatorio.View.RelTicketMedio in 'Relatorio\View\BCC.Relatorio.View.RelTicketMedio.pas' {FraRelTicketMedio: TFrame},
  BCC.Relatorio.View.FluxoCaixa in 'Relatorio\View\BCC.Relatorio.View.FluxoCaixa.pas' {FraRelFluxoCaixa: TFrame},
  BCC.Relatorio.Report.FluxoCaixa in 'Relatorio\Report\BCC.Relatorio.Report.FluxoCaixa.pas' {RelFluxoCaixa},
  BCC.Relatorio.Report.ProdutosVendidos in 'Relatorio\Report\BCC.Relatorio.Report.ProdutosVendidos.pas' {RelProdutosVendidos},
  BCC.Relatorio.Report.TicketMedio in 'Relatorio\Report\BCC.Relatorio.Report.TicketMedio.pas' {RelTicketMedio},
  BCC.Relatorio.Report.VendasDia in 'Relatorio\Report\BCC.Relatorio.Report.VendasDia.pas' {RelVendasDia},
  BCC.View.ManualBase in 'Base\View\BCC.View.ManualBase.pas' {FrmManualBase},
  BCC.Manual.View.AbrirMesa in 'Manual\View\BCC.Manual.View.AbrirMesa.pas' {FrmManualAbrirMesa},
  BCC.Manual.View.InserirProduto in 'Manual\View\BCC.Manual.View.InserirProduto.pas' {FrmManualInserirProduto},
  BCC.Manual.View.InserirServico in 'Manual\View\BCC.Manual.View.InserirServico.pas' {FrmManualInserirServico},
  BCC.Manual.View.InserirJogo in 'Manual\View\BCC.Manual.View.InserirJogo.pas' {FrmManualInserirJogo},
  BCC.Manual.View.VincularCliente in 'Manual\View\BCC.Manual.View.VincularCliente.pas' {FrmManualVincularCliente},
  BCC.Manual.View.FecharMesa in 'Manual\View\BCC.Manual.View.FecharMesa.pas' {FrmManualFecharMesa},
  BCC.Manual.View.IniciarCampeonato in 'Manual\View\BCC.Manual.View.IniciarCampeonato.pas' {FrmManualIniciarCampeonato},
  BCC.Manual.View.EncerrarCampeonato in 'Manual\View\BCC.Manual.View.EncerrarCampeonato.pas' {FrmManualEncerrarCampeonato},
  BCC.Manual.View.RegistrarPartida in 'Manual\View\BCC.Manual.View.RegistrarPartida.pas' {FrmManualRegistrarPartida},
  BCC.Manual.View.AgendarReserva in 'Manual\View\BCC.Manual.View.AgendarReserva.pas' {FrmManualAgendarReserva},
  BCC.Manual.View.CadastrarCampeonato in 'Manual\View\BCC.Manual.View.CadastrarCampeonato.pas' {FrmManualCadastrarCampeonato};

{$R *.res}

begin
  Application.Initialize();
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TDmDados, DmDados);
  Application.CreateForm(TFrmLogin, FrmLogin);
  Application.Run();
end.
